version: '3.8'
services:
  app:
    image: lucasmeunier/episen-sca-lme-back
    container_name: episen-sca-lme-back
    labels:
      - "com.docker.order.name=backend"
      - "com.docker.order.version=4.0.0"
      - "com.docker.order.dockerfile.date=24.11.2020"
    ports:
      - "8080:8080"
    volumes:
      - vol_test:/var/lib
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 1m30s
      timeout: 15s
      retries: 5
      start_period: 50s
    links:
      - "front"
    deploy:
      replicas: 1 #sinon ça saute
      resources:
        limits:
          cpus: '0.50'
          memory: 800m
        reservations:
          cpus: '0.1'
          memory: 100m
      restart_policy:
        condition: on-failure
  front:
    image: lucasmeunier/episen-sca-lme-front
    container_name: episen-sca-lme-front
    labels:
      - "com.docker.order.name=front"
      - "com.docker.order.front.version=4.0.0"
      - "com.docker.order.dockerfile.date=124.11.2020"
    ports:
      - "80:80"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 1m30s
      timeout: 15s
      retries: 5
      start_period: 50s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 800m
        reservations:
          cpus: '0.1'
          memory: 100m
      restart_policy:
        condition: on-failure

volumes:
  vol_test:

