version: '3.8'
services:
  app:
    image: lucasmeunier/episen-sca-lme-back
    labels:
      - "com.docker.order.name=backend"
      - "com.docker.order.version=2.0.0"
      - "com.docker.order.dockerfile.date=18.11.2020"
    ports:
      - "8080:8080"
    volumes:
      - vol_test:/var/lib
    links:
      - "front"
#    deploy:
#      replicas: 2
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 800m
#        reservations:
#          cpus: '0.1'
#          memory: 100m
  front:
    image: lucasmeunier/episen-sca-lme-front
    labels:
      - "com.docker.order.name=backend"
      - "com.docker.order.front.version=2.0.0"
      - "com.docker.order.dockerfile.date=18.11.2020"
    ports:
      - "80:80"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 800m
#        reservations:
#          cpus: '0.1'
#          memory: 100m

volumes:
  vol_test:

