FROM maven:3.6.3-jdk-11-slim AS build
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean install

FROM openjdk:13-jdk-alpine
RUN addgroup -g 1010 springboot && adduser -u 1010 -G springboot -h /home/springboot -D springboot


COPY --from=build /usr/src/app/target/episen-sca-lme-backend-0.0.1-SNAPSHOT.jar /springboot/app/app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/springboot/app/app.jar"]

LABEL com.docker.order.name="backend"
LABEL com.docker.order.version="3.1.0"
LABEL com.docker.order.dockerfile.date="24.11.2020"
